image: node:9.1.0

cache:
  paths:
    - node_modules/
    - yarn.lock

build:
  stage: build
  before_script:
    - yarn
  script:
    - yarn build

test:
  stage: test
gi  script:
    - CI=true yarn test

pages:
  stage: deploy
  script:
    - CI=true yarn build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
