image: node:9.4.0

cache:
  paths:
    - node_modules/
    - yarn.lock

build:
  stage: build
  before_script:
    - yarn
  script:
    - yarn build

test:
  stage: test
  script:
    - CI=true yarn test
