image: node:9.4.0

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

stages:
  - setup
  - build
  - test

setup:
  stage: setup
  script:
    - yarn

build:
  stage: build
  script:
    - yarn build

test:
  stage: test
  script:
    - ls -l
    - CI=true yarn test
